---
title: "Lab 5"
author: "Thorax Hembleecker"
date: "20XX-02-27"
output: pdf_document
---

## 2. Binomial Distribution
```{r 2}
## Density
# A.
dbinom(0, size=5, prob=0.25)
# B.
dbinom(1, size=5, prob=0.25)
## Probability
# C.
pbinom(1, size=5, prob=0.25)
# D.
pbinom(2, size=5, prob=0.25) #2 because P(X<3) = P(X<=3-1)
# E.
1 - pbinom(1, size=5, prob=0.25)
# F.
1 - pbinom(2, size=5, prob=0.25)
# G.
dbinom(c(1,3,4),5,0.25) #probability of multiple outcomes
sum(dbinom(c(1,3,5),5,0.25)) #probability of odd numbers
sum(dbinom(c(0,2,4),5,0.25)) #probability of even numbers
```

## 3. Poisson Distribution
```{r 3}
# A.
dpois(0, 5)
# B.
dpois(1, 5)
# C.
ppois(1, 5)
# D.
ppois(2, 5)
# E.
1 - ppois(1, 5)
# F.
1 - ppois(2, 5)
```

## 4. Hypergeometric Distribution
```{r 4}
# A.
dhyper(x=14, m=70, n=30, k=20)
# B.
phyper(2, 15, 225, 7)
```

## 5. Uniform Distribution
```{r 5}
# A.
punif(8, 1, 12)
# B.
punif(19, 15, 25) - punif(17, 15, 25)
# C.
1 - punif(1.5, 1, 2)
```

## 6. Exponential Distribution
```{r 6}
# A.
pexp(1.3, 4)
# B.
1 - pexp(1.5, 2)
# C.
pexp(5,0.3) - pexp(1,0.3)
```

## 7. Normal Distribution
```{r 7}
# A.
pnorm(3)
# B.
1 - pnorm(3)
# C.
pnorm(3, mean=1, sd=1.5)
# D.
pnorm(2.1,1.3,1.1) - pnorm(0.9,1.3,1.1)
# E.
qnorm(0.2)
# F.
qnorm(0.2,10,3)
# G.
qnorm(0.95)
```